changed the approch of firebase

diff --git a/.github/workflows/frontend-build.yml b/.github/workflows/frontend-build.yml
--- a/.github/workflows/frontend-build.yml
+++ b/.github/workflows/frontend-build.yml
@@ -85,11 +85,19 @@ jobs:
           #  Please find the latest APK attached.
           # attachments: Frontend/android/app/build/outputs/apk/release/app-release.apk
 
-      - name: Decode Firebase Service Account
+      # - name: Decode Firebase Service Account
+      #   run: |
+      #     echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > $RUNNER_TEMP/firebase.json
+      #     test -s firebase.json || (echo "FIREBASE_SERVICE_ACCOUNT secret is missing or invalid" && exit 1)
+      #     echo "Decoded successfully"
+      #     ls -lh $RUNNER_TEMP/firebase.json
+      #     head -n 5 $RUNNER_TEMP/firebase.json
+
+      - name: Create Firebase credentials
         run: |
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > $RUNNER_TEMP/firebase.json
-          test -s firebase.json || (echo "FIREBASE_SERVICE_ACCOUNT secret is missing or invalid" && exit 1)
-          echo "Decoded successfully"
+          echo '${{ secrets.FIREBASE_SERVICE_KEY }}' > $RUNNER_TEMP/firebase.json
+          test -s $RUNNER_TEMP/firebase.json || (echo "FIREBASE_SERVICE_KEY secret is missing or invalid" && exit 1)
+          echo "Created successfully"
           ls -lh $RUNNER_TEMP/firebase.json
           head -n 5 $RUNNER_TEMP/firebase.json
 
